BlogProject/BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loginapp/', include('loginapp.urls')),
    path('', include('blogapp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogProject/blogapp/urls.py
from django.urls import path
from . import views
app_name = 'blogapp'
urlpatterns = [
    path('create_blog',views.Create_Blog,name='create_blog'),
    path('',views.blog_home,name='blog_home'),
    path('edit_blog/<pk>',views.Edit_Blog.as_view(),name='edit_blog'), 
    path('delete_blog/<pk>',views.Delete_Blog.as_view(),name='delete_blog'), 
    path('blog_details/<pk>',views.Blog_Details,name='blog_details'), 
    path('like_blog/<pk>',views.like_blog,name='like_blog'), 
    path('search_blogs',views.search_blogs,name='search_blogs'), 
]

BlogProject/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog_Model(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_author')
    title = models.CharField(max_length=15)
    image = models.ImageField(upload_to='blog_pics')
    description = models.TextField()
    category = models.CharField(max_length=60)
    date_added = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    blog = models.ForeignKey(Blog_Model,on_delete=models.CASCADE,related_name='blog_comment')
    comment = models.CharField(max_length=100)
    uploaded_date = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='liked_user')
    blog = models.ForeignKey(Blog_Model,on_delete=models.CASCADE,related_name='liked_blog')

BlogProject/blogapp/forms.py
from django import forms
from .models import Blog_Model,Comment
from django.forms import TextInput
class Create_Blog_Form(forms.ModelForm):
    class Meta:
        model = Blog_Model
        exclude = ('author',)

class Create_Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('user','blog',)

        widgets = {
            "comment" : TextInput(attrs={
            'style' : 'border:none; border-bottom:2px solid lightgray',
            'placeholder' : 'Enter Comment'
            })
        }

BlogProject/blogapp/views.py
from django.shortcuts import render,HttpResponse
from django.urls import reverse_lazy
from .forms import Create_Blog_Form,Create_Comment_Form
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView,DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Blog_Model,Comment,Like
# Create your views here.

def blog_home(request):
    all_blogs = Blog_Model.objects.all()
    context = {'all_blogs':all_blogs}
    return render(request,'blogapp/blog_home.html',context)


@login_required(login_url='loginapp:login')
def Create_Blog(request):
    form = Create_Blog_Form()
    if request.method == 'POST':
        form = Create_Blog_Form(request.POST,request.FILES)
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.author = request.user
            form_instance.save()
            return HttpResponse('YOUR BLOG IS SUCCESSFULLY MADE!')
        
    dict = {'form':form}
    return render(request,'blogapp/create_blog.html',dict)

class Edit_Blog(LoginRequiredMixin,UpdateView):
    model = Blog_Model
    fields = ('title','image','description','category')
    template_name = ('blogapp/edit_blog.html')

    def get_success_url(self):
        return reverse_lazy('loginapp:user_profile')


class Delete_Blog(LoginRequiredMixin,DeleteView):
    model = Blog_Model
    template_name = ('blogapp/delete_blog.html')

    def get_success_url(self):
        return reverse_lazy('loginapp:user_profile')
    
def Blog_Details(request,pk):
    blog_model = Blog_Model.objects.get(pk=pk)
    form = Create_Comment_Form()
    current_user = request.user
    comments = Comment.objects.filter(blog=blog_model)
    if current_user.is_authenticated:

        if request.method == 'POST':
            form = Create_Comment_Form(request.POST)
            if form.is_valid():
                form_instance = form.save(commit=False)
                form_instance.user = request.user
                form_instance.blog = blog_model
                form_instance.save()
                return HttpResponse('Congratulations! Your Comment Is Published!')
        dict = {'form':form,'blog_model':blog_model,'comments':comments}
        return render(request,'blogapp/blog_details.html',dict)
    else:
        dict = {'blog_model':blog_model,'comments':comments}
        return render(request,'blogapp/blog_details.html',dict)
    


@login_required
def like_blog(request,pk):
    blog_model = Blog_Model.objects.get(pk=pk)
    like = Like.objects.filter(user=request.user,blog=blog_model).first()
    if like:
        like.delete()
        has_liked = False
    else:
        Like.objects.create(user=request.user,blog=blog_model)
        has_liked = True
    liked_count = Like.objects.filter(blog=blog_model).count()
    context= {'has_liked':has_liked,'blog_model':blog_model,'liked_count':liked_count}
    return render(request,'blogapp/blog_details.html',context)

def search_blogs(request):
    searched_query = request.GET.get('search')
    searched_results = Blog_Model.objects.filter(title__icontains= searched_query)
    searched_results_count = Blog_Model.objects.filter(title__icontains= searched_query).count()
    context = {
        "searched_results":searched_results,
        "searched_query":searched_query,
        "searched_results_count":searched_results_count
    }
    return render(request,'blogapp/search.html',context)

BlogProject/templates/blogapp/blog_details.html
{% extends 'base.html' %}

{% block titleblock %}
Blog Details
{% endblock titleblock %}

{% block bodyblock %}
<script src="https://kit.fontawesome.com/4afee10683.js" crossorigin="anonymous"></script>
<style>
    .main-div {
        display: flex;
        flex-direction: column;
    }

    .heading-div {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .title {
        font-size: 60px;
        font-weight: bold;
        text-decoration: underline;
        font-family: Georgia, 'Times New Roman', Times, serif;
    }

    .category,
    .date {
        padding-left: 0;
        margin-left: 0;
        font-family: Georgia, 'Times New Roman', Times, serif;
        font-size: 30px;
    }

    .category-span {
        color: aqua;
    }

    .date_added {
        color: lightgray;
    }

    .body-div {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 60px;
    }

    .image {
        height: 450px;
        width: 855px;
        margin-bottom: 50px;
    }

    .comments_div {
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
        align-items: flex-start;
    }

    .img_comment {
        width: 30px;
        height: 40px;
        border-radius: 20px;
    }

    .pic_div {
        margin-right: 25px;
        margin-left: 15px;
    }

    .comment_username {
        font-size: 25px;
        font-weight: bold;
    }

    .comment_date {
        font-size: 15px;
        color: rgb(114, 108, 108);
    }

    hr {
        margin-top: 40px;
        margin-bottom: 25px;
    }

    .like_div i {
        font-size: 50px;


    }

    .like_div {
        margin: 0 200px;
    }

    .like_div h4 {
        font-size: 25px;
        color: black;
        font-weight: 500;
        font-style: italic;
    }
</style>

<div class="main-div">
    <div class="heading-div">
        <span class="title">{{blog_model.title}}</span>
        <span class="category">Category : <span class="category-span">{{blog_model.category}}</span></span>
        <span class="date">Date Published : <span class="date_added">{{blog_model.date_added}}</span></span>
    </div>
    <div class="body-div">
        <img src="/media/{{blog_model.image}}" class="image">
        <span>{{blog_model.description}}</span>
    </div>

    {%if user.is_authenticated%}
    {%if has_liked%}
    <div class="like_div">
        <form action="{%url 'blogapp:like_blog' pk=blog_model.pk%}" method="post">
            {%csrf_token%}
            <button type="submit" value="like" name="like" id="like"><i class="fa-solid fa-heart"></i></button>
        </form>
        <h4>Likes : {{liked_count}}</h4>
    </div>

    {%else%}
    <div class="like_div">
        <form action="{%url 'blogapp:like_blog' pk=blog_model.pk%}" method="post">
            {%csrf_token%}
            <button type="submit" value="like" name="like" id="like"><i class="fa-regular fa-heart"></i></button>
        </form>
        <h4>Likes : {{liked_count}}</h4>
    </div>

    {%endif%}
    {%endif%}
</div>



<hr>

<style>
    @import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,700&display=swap");

    .comment_container {
        display: flex;
        gap: 30px;
        margin: 20px 50px;
        font-family: "Roboto", sans-serif;
    }

    .comment_image img {
        height: 35px;
        width: 35px;
        border-radius: 50%;
    }

    .comment_content {
        display: flex;
        flex-direction: column;
        gap: 7px;
        justify-content: flex-start;
    }

    .comment_heading {
        display: flex;
        gap: 5px;
    }

    .comment_heading h3 {
        font-size: 15px;
        color: #212121;
    }

    .comment_heading p {
        font-size: 13px;
        color: #2121218A;
    }

    .form_div {
        margin-left: 50px;
    }

    .form_div form {
        display: flex;
        gap: 10px;
        align-items: center;
    }

    .form_div form button {
        padding: 8px;
        background-color: turquoise;
        border-radius: 5px;
        transition: 0.4s ease-in;
    }

    form button:hover {
        opacity: 0.7;
    }
</style>

{%for comment in comments%}
<div class="comment_container">
    {%if comment.user.user_profile.profile_pic%}
    <div class="comment_image">

        <img src="{{comment.user.user_profile.profile_pic.url}}" alt="User Profile Pic">
    </div>
    {%else%}
    <div class="comment_image">
        <img src="/media/profile_pics/user.png" alt="Default User Image">
    </div>
    {%endif%}
    <div class="comment_content">
        <div class="comment_heading">
            <h3>{{comment.user.username}}</h3>
            <p>{{comment.uploaded_date}}</p>
        </div>
        <div class="comment_body">
            <p>{{comment.comment}}</p>
        </div>
    </div>
</div>
{%empty%}
<h1>No Comments!</h1>
{%endfor%}

<div class="form_div">
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Comment!</button>
    </form>

</div>


{% endblock bodyblock %}

BlogProject/templates/blogapp/blog_home.html
{% extends 'base.html' %}

{%block titleblock%}
Ultra Blogger
{%endblock titleblock%}

{%block bodyblock%}

<style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap');

    /* Hero Section  */
    .hero {
        background-image: url('media/extra_pics/hd_background.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        height: 850px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .text-center {
        background-color: rgb(47, 46, 47);
        width: 800px;
        line-height: normal;
        font-family: "Roboto", sans-serif;
        font-weight: 700;
        font-style: italic;
    }

    .text-center h1 {
        color: white;
        font-size: 89px;
        text-align: center;
    }

    .text-center p {
        font-size: 21px;
        color: #B3B3B3;
        text-align: center;
    }

    /* Card Section  */
    .cards {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        grid-template-rows: repeat(2, 1fr);
        gap: 10px;
        margin: 100px;
    }

    .card {
        border: 2px solid lightgray;
        font-family: 'Roboto Condensed', sans-serif;
        width: 362px;
    }

    .card_image img {
        height: 168.75px;
        object-fit: cover;
        width: 100%;
        transition: transform ease-in 0.3s;
    }

    .card:hover .card_image img {
        transform: scale(0.95);
        transition: transform ease-in 0.3s;

    }

    .card_desc_heading {
        display: flex;
        gap: 8px;
        align-items: center;
        margin: 20px 15px;
    }

    .desc_heading_img img {
        width: 32px;
        height: 32px;
        border-radius: 50%;
    }

    .desc_heading_rest {
        font-size: 12px;
        color: #4b4848;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
    }

    .card_desc_desc {
        margin: 0px 15px;
    }

    .card_desc_desc p {
        color: #2f2e2e;
        font-size: 18px;
    }

    .card_footer {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 10px 15px;
    }

    .divider {
        margin: 0px 15px;
    }

    /* Footer Section  */

    footer {
        display: flex;
        flex-direction: column;
        background-color: rgb(47, 46, 46);
        color: white;
        padding-top: 70px;
    }

    .icons {
        font-size: 35px;
        display: flex;
        justify-content: space-evenly;
        align-items: center;
        transition: 0.1s ease-in;
        cursor: pointer;
    }

    .footer_text {
        font-size: 20px;
        text-align: center;
        padding-top: 30px;
        font-weight: 600;
        font-family: 'Roboto Condensed', sans-serif;
    }

    .icons .fa-twitter:hover {
        color: rgb(29, 161, 242);
    }

    .icons .fa-linkedin-in:hover {
        color: #0072b1;
    }

    .icons .fa-facebook-f:hover {
        color: #4267b2;
    }

    .icons .fa-instagram:hover {
        color: #C13584;
    }

    .icons .fa-youtube:hover {
        color: #FF0000;
    }
</style>


<section class="hero">
    <div class="text-center">
        <h1>Ultra Blogger</h1>
        <p>Modern Blogging Hub!</p>
    </div>
</section>

<section class="cards">
    {%for blog in all_blogs%}
    <div class="card">
        <div class="card_image"><a href="{%url 'blogapp:blog_details' pk=blog.pk%}">
                <img src="{{blog.image.url}}" alt="Blog Image"></a></div>

        <div class="card_desc">
            <div class="card_desc_heading">
                <div class="desc_heading_img">
                    {%if blog.author.user_profile.profile_pic%}
                    <img src="{{blog.author.user_profile.profile_pic}}" alt="User Profile Pic">
                    {%else%}
                    <img src="media/profile_pics/user.png" alt="User Image">
                    {%endif%}
                </div>
                <div class="desc_heading_rest">
                    <div>{{blog.author}}</div>
                    <div>{{blog.date_added}}</div>
                </div>
            </div>
            <div class="card_desc_desc">
                <p>{{blog.title}}</p>
            </div>
        </div>
        <hr class="divider">
        <div class="card_footer">
            <div class="comment">
                <i class="fa-regular fa-comment"></i>
                <span>{{blog.blog_comment.count}}</span>
            </div>
            <div class="likes">
                <span>{{blog.liked_blog.count}}</span>
                <i class="fa-regular fa-heart" style="color: red;"></i>
            </div>
        </div>
    </div>
    {%endfor%}
</section>

<footer>
    <div class="icons">
        <i class="fa-brands fa-twitter"></i>
        &#47;
        <i class="fa-brands fa-linkedin-in"></i>
        &#47;
        <i class="fa-brands fa-facebook-f"></i>
        &#47;
        <i class="fa-brands fa-instagram"></i>
        &#47;
        <i class="fa-brands fa-youtube"></i>
    </div>
    <div class="footer_text">
        &#x2022; 2023 by Ultra Blogger, Powered and Created by WEB DUDE
    </div>
</footer>
{%endblock bodyblock%}

BlogProject/templates/blogapp/create_blog.html
{% extends 'base.html' %}

{% block titleblock %}
    Create Blog
{% endblock titleblock %}

{% block bodyblock  %}
    <h1 style="text-decoration: underline; font-style: italic; font-weight: bold;">Create Your Blog!</h1>
    <form method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button class="btn btn-outline-success">Create!</button>
    </form>
{% endblock  %}

BlogProject/templates/blogapp/delete_blog.html
{% extends 'base.html' %}

{% block titleblock %}
    Delete Blog!
{% endblock titleblock %}

{% block bodyblock %}
    <form method="post">
        {%csrf_token%}
        <h1>Do You Want To Delete {{object.title}}</h1>
        <button type="submit" class="btn btn-outline-success" value="Confirm">Delete!</button>
    </form>
{% endblock bodyblock %}

BlogProject/templates/blogapp/edit_blog.html
{% extends 'base.html' %}

{% block titleblock %}
Update Blog!
{% endblock titleblock %}

{% block bodyblock %}
    <form method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button class="btn btn-outline-success" type="submit">Update!</button>
    </form>
{% endblock bodyblock %}

BlogProject/templates/blogapp/search.html
{% extends 'base.html' %}

{% block titleblock %}

Search Resulsts
{% endblock titleblock %}

{% block bodyblock %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap');

    .search_div {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin: 30px 0px;
        justify-content: center;
    }

    /* INPUT DIV STYLING  */
    .input_div {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 5vh;
        border: 1px solid gray;
    }

    h2 {
        font-family: 'Roboto Condensed', sans-serif;
        letter-spacing: 2px;
        font-size: 40px;
        margin-bottom: 60px;
    }

    input {
        width: 60vw;
        padding: 7px 0px;
        border: none;
        text-align: start;
    }

    input:focus {
        outline: none;
    }

    input::placeholder {
        font-size: 20px;
        font-family: 'Roboto Condensed', sans-serif;
    }

    .form_button {
        border: none;
        margin-right: 5px;
    }

    /* SEARCHED INFO STYLING */

    .results {
        font-size: 20px;
        font-family: 'Roboto Condensed', sans-serif;
        margin: 15px 0px;
    }

    .searched_results {
        display: flex;
        align-items: center;
        gap: 5vw;
        margin: 30px 0px;
    }

    .searched_results:hover .search_image img {
        transform: scale(0.95);
        transition: transform ease-in-out 0.3s;
    }

    .search_image img {
        transition: transform ease-in-out 0.3s;
        width: 176px;
        height: 124px;
        object-fit: cover;
        object-position: 50% 50%;
    }

    .search_rest a {
        text-decoration: none;
    }

    .search_rest h3 {
        font-size: 20px;
        font-style: italic;
        color: rgb(47, 46, 47);
    }

    .search_rest h3:hover {
        text-decoration: underline;
    }

    .search_rest p {
        font-size: 14px;
        color: rgb(47, 46, 47);
        width: 40vw;
        word-wrap: break-word;
    }
</style>


<div class="search_div">
    <h2>Search Results</h2>
    <div class="input_div">
        <button class="form_button" form="search_form"><i class="fa-solid fa-magnifying-glass"></i></button>
        <form action="{%url 'blogapp:search_blogs'%}" class="search_form" id="search_form">
            <input type="search" name="search" id="search" placeholder="Search...">
        </form>
    </div>

    <div class="searched_info">
        <p class="results">{{searched_results_count}} found for {{searched_query}}</p>
        {%for search in searched_results%}
        <div class="searched_results">
            <div class="search_image">
                <img src="{{search.image.url}}" alt="Search Image">
            </div>
            <div class="search_rest">
                <a href="{%url 'blogapp:blog_details' pk=search.pk%}">
                    <h3>{{search.title}}</h3>
                </a>
                <p>{{search.description|truncatewords:35}}</p>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

{% endblock bodyblock %}