BlogProject/BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loginapp/', include('loginapp.urls')),
    path('', include('blogapp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogProject/blogapp/urls.py
from django.urls import path
from . import views
app_name = 'blogapp'
urlpatterns = [
    path('create_blog',views.Create_Blog,name='create_blog'),
    path('',views.blog_home,name='blog_home'),
    path('edit_blog/<pk>',views.Edit_Blog.as_view(),name='edit_blog'), 
    path('delete_blog/<pk>',views.Delete_Blog.as_view(),name='delete_blog'), 
    path('blog_details/<pk>',views.Blog_Details,name='blog_details'), 
    path('like_blog/<pk>',views.like_blog,name='like_blog'), 
    path('search_blogs',views.search_blogs,name='search_blogs'), 
]

BlogProject/loginapp/urls.py
from django.urls import path
from . import views
app_name = 'loginapp'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login_user', views.login_page, name='login'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

BlogProject/loginapp/models.py
from django.db import models
from django.contrib.auth.models import User
# To automatically create one to one object
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics')
    first_name = models.CharField(max_length=50,blank=True)
    last_name = models.CharField(max_length=50,blank=True)
    phone_number = models.CharField(max_length=11,blank=True)
    website = models.URLField(blank=True)

@receiver(post_save,sender= User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save,sender= User)
def save_profile(sender,instance,**kwargs):
    instance.user_profile.save()

BlogProject/loginapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',)

class Edit_Profile_Form(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

BlogProject/loginapp/views.py
from django.contrib.auth import login,authenticate
from .forms import SignUpForm,Edit_Profile_Form
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import UserProfile
from django.contrib.auth.decorators import login_required

from blogapp.models import Blog_Model
# Create your views here.


def signup(request):
    form = SignUpForm
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Signed Up Successfully!')

    dict = {'form': form}
    return render(request, 'loginapp/signup.html', dict)


def login_page(request):
    form = AuthenticationForm
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # return HttpResponse('Logged In Successfully!')
                return HttpResponseRedirect(reverse('loginapp:user_profile'))
    dict = {'form': form}
    return render(request, 'loginapp/login.html', dict)

@login_required(login_url='loginapp:login')
def user_profile(request):
    current_user = request.user
    blogs = Blog_Model.objects.filter(author=current_user)
    dict = {'blogs':blogs}
    return render(request,'loginapp/profile.html',dict)

@login_required(login_url='loginapp:login')
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = Edit_Profile_Form(instance=current_user)
    if request.method == 'POST':
        form = Edit_Profile_Form(request.POST,request.FILES,instance=current_user)
        if form.is_valid():
            form.save()
            form = Edit_Profile_Form(instance=current_user)
            return HttpResponseRedirect(reverse('loginapp:user_profile'))
    dict = {'form':form}
    return render(request,'loginapp/edit_profile.html',dict)

BlogProject/templates/loginapp/edit_profile.html
{% extends 'base.html'%}
{%block titleblock%}
Edit Profile
{%endblock%}
{%block bodyblock%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-outline-primary">Edit Profile</button>
</form>
{%endblock%}

BlogProject/templates/loginapp/login.html
{% extends 'base.html'%}
{%block titleblock%}
Login!
{%endblock%}
{%block bodyblock%}



<style>
    body {
        background-image: url('/media/extra_pics/background.jpeg');
    }

    .main-div {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 150px;
        background-color: burlywood;
        border: 1px solid lightgray;
        margin-left: 200px;
        margin-right: 200px;
        padding-bottom: 50px;
        border-radius: 20px;
    }

    .heading {
        font-weight: bold;
        font-style: italic;
        text-decoration: underline;
    }

    .heading-div {
        margin-bottom: 30px;
    }

    .username-div {
        margin-bottom: 50px;
    }

    .link {
        font-size: 25px;
    }

    .link:hover {
        font-weight: bold;
    }

    .link:active {
        font-style: italic;
    }

    .link-to-sign-up-div {
        margin-top: 20px;
        margin-bottom: 10px;
    }
</style>

<form method="post">
    {%csrf_token%}

    <div class="main-div">
        <div class="heading-div">
            <h1 class="heading">Login Into Your Account!</h1>
        </div>
        <div class="username-div">
            Username : {{form.username}}
        </div>
        <div class="password-div">
            Password : {{form.password}}
        </div>
        <div class="link-to-sign-up-div">
            <a href="{%url 'loginapp:signup'%}" class="link">Don`t Have an account!</a>
        </div>
        <div class="login-button-div">
            <button type="submit" class="btn btn-outline-success">Login</button>
        </div>
    </div>
</form>
{%endblock%}

BlogProject/templates/loginapp/profile.html
{%extends 'base.html'%}

{%block titleblock%}
USER PROFILE
{%endblock%}

{%block bodyblock%}
<style>
    body {
        background-color: lightgray;
    }

    .upper-main-div {
        margin-right: 100px;
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
    }

    img {
        width: 200px;
        height: 250px;
        border-radius: 100px;
    }

    .img-div {
        margin-right: 200px;
        margin-left: 0;
    }

    h3 {
        font-size: 65px;
    }

    h5 {
        font-size: 30px;
    }

    .no-blogs:hover {
        font-style: italic;
    }

    .edit-profile {
        position: fixed;
        right: 25px;
        top: 100px;
    }

    .down-div {
        margin-top: 100px;
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        margin-left: 75px;
    }
    .blog_image{
        border-radius: 0;
        height: 200px;
        width: 200px;
    }
</style>
<a href="{%url 'loginapp:edit_profile'%}"><button class="btn btn-outline-warning edit-profile">Edit Profile</button></a>
<div class="upper-main-div">
    <div class="img-div">
        {%if user.user_profile.profile_pic%}
        <img src="/media/profile_pics/{{user.user_profile.profile_pic}}" alt="">
        {%else%}
        <img src="/media/profile_pics/user.png" alt="">
        {%endif%}
    </div>
    <div class="desc-div">
        <div class="heading">
            <h3>Likes : 0 &nbsp; Blogs : 0</h3>
        </div>
        <div class="description">
            <h5>Username : {{user.username}}</h5>
            <h5>First Name : {{user.user_profile.first_name}}</h5>
            <h5>Last Name : {{user.user_profile.last_name}}</h5>
            <h5>Contact Number : {{user.user_profile.phone_number}}</h5>
            <h5>Website : {{user.user_profile.website}}</h5>
        </div>
    </div>

</div>
<div class="down-div">

    {%if blogs%}
    <h1 style="text-decoration: underline; font-weight: bold; font-style: oblique;">Blogs</h1>
    <hr>
    {%for blog in blogs%}
    <a href="{%url 'blogapp:blog_details' pk=blog.pk%}"><img src="/media/{{blog.image}}" class="blog_image"></a>
    <a href="{%url 'blogapp:edit_blog' pk=blog.pk%}"><button class="btn btn-outline-warning">Edit</button></a>
    <a href="{%url 'blogapp:delete_blog' pk=blog.pk%}"><button class="btn btn-outline-danger">Delete</button></a>
    {%endfor%}
    {%else%}
    <h3>NO BLOGS POSTED</h3>
    {%endif%}

</div>
{%endblock%}

BlogProject/templates/loginapp/signup.html
{% extends 'base.html'%}
{%block titleblock%}
Sign Up!
{%endblock%}
{%block bodyblock%}
<style>
    body {
        background-image: url('/media/extra_pics/background.jpeg');
    }

    .main-div {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin-top: 150px;
        background-color: burlywood;
        border: 1px solid lightgray;
        margin-left: 200px;
        margin-right: 200px;
        padding-bottom: 50px;
        border-radius: 20px;
    }

    .heading {
        font-weight: bold;
        font-style: italic;
        text-decoration: underline;
    }

    .heading-div {
        margin-bottom: 30px;
    }

    .username-div {
        margin-bottom: 50px;
    }

    .link {
        font-size: 25px;
    }

    .link:hover {
        font-weight: bold;
    }

    .link:active {
        font-style: italic;
    }

    .link-to-sign-up-div {
        margin-top: 20px;
        margin-bottom: 10px;
    }
    .password-div{
        margin-bottom: 30px;
    }
</style>

<form method="post">
    {%csrf_token%}

    <div class="main-div">
        <div class="heading-div">
            <h1 class="heading">Sign Up For Free!</h1>
        </div>
        <div class="username-div">
            Username : {{form.username}}
        </div>
        <div class="password-div">
            Password 1 : {{form.password1}}
        </div>
        <div class="password-div">
            Password 2 : {{form.password2}}
        </div>
        <div class="password-div">
            Email : {{form.email}}
        </div>
        <div class="link-to-sign-up-div">
            <a href="{%url 'loginapp:login'%}" class="link">Have an account!</a>
        </div>
        <div class="login-button-div">
            <button type="submit" class="btn btn-outline-success">Sign Up</button>
        </div>
    </div>
</form>
{%endblock%}