BlogProject/BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loginapp/', include('loginapp.urls')),
    path('', include('blogapp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogProject/blogapp/urls.py
from django.urls import path
from . import views
app_name = 'blogapp'
urlpatterns = [
    path('create_blog',views.Create_Blog,name='create_blog'),
    path('',views.blog_home,name='blog_home'),
    path('edit_blog/<pk>',views.Edit_Blog.as_view(),name='edit_blog'), 
    path('delete_blog/<pk>',views.Delete_Blog.as_view(),name='delete_blog'), 
    path('blog_details/<pk>',views.Blog_Details,name='blog_details'), 
    path('like_blog/<pk>',views.like_blog,name='like_blog'), 
    path('search_blogs',views.search_blogs,name='search_blogs'), 
]

BlogProject/loginapp/urls.py
from django.urls import path
from . import views
app_name = 'loginapp'
urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login_user', views.login_page, name='login'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
]

BlogProject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titleblock%} {%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4afee10683.js" crossorigin="anonymous"></script>
</head>

<body>
    {%include 'navbar.html'%}
    {%block bodyblock%} {%endblock%}
</body>

</html>

BlogProject/templates/navbar.html
<style>
    .images {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
        margin: 0px 20px;
    }

    .images img {
        width: 25px;
        height: 25px;
        object-fit: cover;
    }
</style>


<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Ultra Blogger</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {%if user.is_authenticated%}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'blogapp:create_blog'%}">Create Blog</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Options
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{%url 'loginapp:user_profile'%}">Profile</a></li>
                        <li><a class="dropdown-item" href="{%url 'loginapp:edit_profile'%}">Edit Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Logout</a></li>
                    </ul>
                </li>
            </ul>
            {%else%}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'loginapp:login'%}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'loginapp:signup'%}">Sign Up!</a>
                </li>
            </ul>
            {%endif%}
            <form class="d-flex" role="search" action="{%url 'blogapp:search_blogs'%}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search"
                    id="search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="images">
                <img src="/media/extra_pics/twitter.png" alt="Twitter">
                <img src="/media/extra_pics/linkedin.png" alt="Linkedin">
                <img src="/media/extra_pics/facebook.png" alt="facebook">
            </div>
        </div>
    </div>
</nav>